version: '3'

networks:
  private:
  public:
    external:
      name: web
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    labels:
      - traefik.backend=yii2vue
      - traefik.docker.network=web
      - traefik.frontend.rule=Host:yii2vue.lokal
      - traefik.port=80
    networks:
      - private
      - public
    volumes:
      - .:/srv/app